[package]
name = "serial-temp-sense-log"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
chrono = "0.4.22"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }